 version: '3.3'
 services:
   jenkins:
     image: jenkins:jcasc
     privileged: true
     user: root
     ports:
       - 8080:8080
     container_name: my-jenkins
     environment: 
       - JENKINS_ADMIN_ID=${ADMIN_ID}
       - JENKINS_ADMIN_PASSWORD=${ADMIN_PASSWORD}
 
      
      
